### ISSUE TITLE
Problem with Module Path

### ISSUE THREAD

**Issue by Wemo99** [Maasq/NPC-Engineer#14]
I am running the software from a USB memory stick so that I can transfer a working copy of my library between desktop/laptop and work machine (for lunchtime tinkering).  Note USB drives can be assigned to different drives on different machines.

To accomplish this I use relative paths in the configuration.  i.e. ".\Library\\" whene the "." signifies the folder where NPC Engineer .EXE is running from. 

e.g.  NPC Engineer is installed in D:\Apps\NPC Engineer\\"

Beneath NPC Engineer folder I have created a "Projects" folder and a "Library" folder (for NPC's) to old the .NPC file and images.

Config screens are as follows:
![image](https://user-images.githubusercontent.com/35747456/35305436-2b35edfe-0091-11e8-8c91-86c3b72220c9.png)

When I create a Project, I also set the Project to a relative path ".\Projects\\" :

![image](https://user-images.githubusercontent.com/35747456/35305817-d4de2172-0092-11e8-81e7-9fd8e27907d1.png)

When I exit from NPC Engineer and restart the application the loaded Module Path is changed:

![image](https://user-images.githubusercontent.com/35747456/35305932-49769686-0093-11e8-8e65-7d4a23419470.png)

Changing this back and clicking close seems to be OK (rather than save the project).

Before and after images of the NPC Engineer.ini is:

![image](https://user-images.githubusercontent.com/35747456/35306124-32101c5a-0094-11e8-84f3-2756e5c4b458.png)

The contents of the Test Title.ini file (project .ini file) is:

ModPath=.\Projects\Test Title\

My guess the process is:

(1) The program starts
(2) The program reads the NPC Engineer.ini file for the current ProjectPath
(3) Opens the current ProjectPath project .ini file and reads the ModPath config setting  from there
(4) It should then populate the contents from ModPath setting (3) into the Manage Project screen/Module Path text field.

It appears to be failing at somepoint in the above process....

**Comment by Maasq** [comment]
Updating the file path storage seems to fix this nicely, along with a couple of other niggles.
