### ISSUE TITLE
Bad XML generated when entering formatted text in description box...

### ISSUE THREAD

**Issue by TheoGeek** [Maasq/NPC-Engineer#15]
OK...TINY bug report. When entering formatted text like this:

<p><i>Gablins are awesome!</p>
<p>(Gablins actually aren't awesome, but they think they are, and they tell everyone about it!)</i></p>

in the description field, it will generate XML like this:

Gablin</link>
\<p>\<i>Gablins are awesome!\</p>
\<p>Gablins actually aren't awesome, but they think they are, and they tell everyone about it!\</i>\</p>

FG does not like that, it complains:

"Database Error: A XML parse error occurred processing file Monsters_NPCs:db.xml - Error on line 123: Error reading end tag."

I don't know XML well, so I checked the Gablin XML against an online XML parser, and sure enough, it also erred. It wants the \</i> to occur before the \</p> on the first line of descriptive text and a \<i> to appear after the <p> on the second line of descriptive text. 

Right now, I'm manually adding an "unformatted period" at the end of a paragraph if the formatting continues to the next paragraph, but it would be nice to not have to do that.

Regardless, GREAT work on an awesome tool. I've used this thing far more than I though I would!

**Comment by Maasq** [comment]
I have fixed this (and an equivalent bug with <b>) as far as I am able. There may well still be situations that produce issues and I'll have to deal with them as they arise.
