### ISSUE TITLE
Language non-weapon actions and reactions not parsing, v0.9.22

### ISSUE THREAD

**Issue by Jmilesy** [Maasq/NPC-Engineer#2]
A couple of issues on the roll 20 version as follows:

Languages do not seem to parse for any import

![image](https://user-images.githubusercontent.com/34949583/34448738-2b0a1236-ece8-11e7-98fd-29cd74147b5f.png)

actions with recharge or reactions do not parse:
![image](https://user-images.githubusercontent.com/34949583/34448763-8719f938-ece8-11e7-91a8-186d9229f528.png)

raw data for each are as follows:
`"name": "Broom of Animated Attack",
"size": "Small",
"type": "Construct",
"alignment": "unaligned",
"AC": "15 (natural armor)",
"HP": "17 (5d6)",
"speed": "0 ft., fly 50 ft. (hover)",
"strength": 10,
"dexterity": 17,
"constitution": 10,
"intelligence": 1,
"wisdom": 5,
"charisma": 1,
"challenge": "1/4",
"traits": [{
"name": "Antimagic Susceptibility",
"text": "The broom is incapacitated while in the area of an antimagic field. If targeted by dispel magic, the broom must succeed on a Constitution saving throw against the caster's spell DC or fall unconscious for 1 minute."
}, {
"name": "False Appearance",
"text": "While the broom remains motionless and isn't flying, it is indistinguishable from a normal broom."
}],
"actions": [{
"name": "Multiattack",
"text": "The broom makes two melee attacks."
}, {
"name": "Broomstick",
"text": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 5 (1d4 + 3) bludgeoning damage."
}],
"damageImmunities": "poison, psychic",
"conditionImmunities": "blinded, charmed, deafened, exhaustion, frightened, paralyzed, petrified, poisoned, prone",
"senses": "blindsight 30 ft. (blind beyond this radius)",
"languages": "None",
"reactions": [{
"name": "Animated Attack",
"text": "If the broom is motionless and a creature grabs hold of it, the broom makes a Dexterity check contested by the creature's Strength check. If the broom wins the contest, it flies out of the creature's grasp and makes a melee attack against it with advantage on the attack roll."
}]
`

and

`"name": "Ezmerelda d'Avenir",
"size": "Medium",
"type": "Humanoid (human)",
"alignment": "chaotic good",
"AC": "17 (+1 studded leather armor)",
"HP": "82 (11d8 + 33)",
"speed": "30 ft.",
"strength": 14,
"dexterity": 19,
"constitution": 16,
"intelligence": 16,
"wisdom": 11,
"charisma": 17,
"challenge": "8",
"traits": [{
"name": "Special Equipment",
"text": "In addition to her magic armor and weapons, Ezmerelda has two potions of greater healing, six vials of holy water, and three wooden stakes."
}, {
"name": "Spellcasting",
"text": "Ezmerelda is a 7th-level spellcaster. Her spellcasting ability is Intelligence (spell save DC 14, +6 to hit with spell attacks). Ezmerelda has the following wizard spells prepared:\nCantrips (at will): fire bolt, light, mage hand, prestidigitation\n1st level (4 slots): protection from evil and good, magic missile, shield\n2nd level (3 slots): darkvision, knock, mirror image\n3rd level (3 slots): clairvoyance, lightning bolt, magic circle\n4th level (1 slot): greater invisibility"
}],
"actions": [{
"name": "Multiattack",
"text": "Ezmerelda makes three attacks: two with her +1 rapier and one with her +1 handaxe or her silvered shortsword."
}, {
"name": "Rapier +1",
"text": "Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 9 (1d8 + 5) piercing damage."
}, {
"name": "Handaxe +1",
"text": "Melee or Ranged Weapon Attack: +6 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 6 (1d6 + 3) slashing damage."
}, {
"name": "Silvered Shortsword",
"text": "Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 7 (1d6 + 4) piercing damage."
}, {
"name": "Curse",
"recharge": "Recharges after a Long Rest",
"text": "Ezmerelda targets one creature that she can see within 30 feet of her. The target must succeed on a DC 14 Wisdom saving throw or be cursed. While cursed, the target has vulnerability to one type of damage of Ezmerelda's choice. The curse lasts until ended with a greater restoration spell, a remove curse spell, or similar magic. When the curse ends, Ezmerelda takes 3d6 psychic damage."
}, {
"name": "Evil Eye",
"recharge": "Recharges after a Short or Long Rest",
"text": "Ezmerelda targets one creature she can see within 10 feet of her and casts one of the following spells on the target (save DC 15), requiring neither somatic nor material components to do so: animal friendship, charm person, or hold person. If the target succeeds on the initial saving throw, Ezmerelda is blinded until the end of her next turn. Once a target succeeds on a saving throw against this effect, it is immune to the Evil Eye power of all Vistani for 24 hours."
}],
"savingThrows": "Wis +3",
"skills": "Acrobatics +7, Arcana +6, Deception +9, Insight +3, Medicine +3, Perception +6, Performance +6, Sleight of Hand +7, Stealth +7, Survival +6",
"languages": "Common, Elvish"
`

**Comment by Maasq** [comment]
I have rewritten the import translator and it works flawlessly with these two examples and the original example.  Most issues were caused by items appearing in a different order, so the rewritten code deals with this.
This issue also prompted a bug fix - the 'blind beyond' condition wasn't being picked up on import.
