### ISSUE TITLE
Tooltip Timeout

### ISSUE THREAD

**Issue by gerry3246** [Maasq/NPC-Engineer#27]
Please extend the tooltip timeout. Some of them are lengthy, and 3 seconds isnt long enough to read it. How about 10 seconds?

**Comment by Maasq** [comment]
Great idea. I decided to implement this as an option - you can set the length of the tooltip display in the Settings dialogue. Look for this in the next release, sometime this week.

**Comment by Maasq** [comment]
Fully implemented and released on the website.
