### ISSUE TITLE
NPC Modules fail to load into Fantasy Grounds

### ISSUE THREAD

**Issue by The-Kergan** [Maasq/NPC-Engineer#28]
I started using your excellent parser to generate NPCs from Adventures in Middle Earth source books to 5E. Last wee I was able to successfully create a module of ~100 NPCs and use it within Fantasy Grounds.

Today I installed the latest version of the Engineer Suite and ran into a problem when I attempted to load a saved module:

**Database Error: A XML parse error occurred processing file AiME NPC - Loremaster Guide:client.xml - Error on line 156: Error reading end tag.**

I renamed the mod file in zip format to assist troubleshooting.

[AiME NPC  Loremaster Guide.zip](https://github.com/Maasq/NPC-Engineer/files/2522036/AiME.NPC.Loremaster.Guide.zip)

Any advice would be gratefully received.

Sincerely, The_Kergan

**Comment by Maasq** [comment]
There seems to be an issue in placing a bulleted list at the very end of a description box (your 'townguard' character). I will look into this.

If you could send me the saved NPC file for this character it would help a lot.

Maasq

**Comment by Maasq** [comment]
I'm going to mark this as 'closed' for now. I made some changes to the coding, but you'll need to reformat the 'guard' character. Good luck!

Maasq
