### ISSUE TITLE
NPC Engineer 0.9.23 hanging at Splash on Launch

### ISSUE THREAD

**Issue by MythikWolf** [Maasq/NPC-Engineer#3]
Version: 0.9.23

Downloaded from website, copied to folder and ran the executable.  Upon running it, the program halted at the splash image and just remained there.

Suspected culprit: Windows Firewall.

**Comment by MythikWolf** [comment]
![image](https://user-images.githubusercontent.com/4665296/34456841-8da1798a-ed55-11e7-9c81-432122792636.png)

Errors seen.

**Comment by MythikWolf** [comment]
![image](https://user-images.githubusercontent.com/4665296/34456997-5851b458-ed59-11e7-9b8f-fb6bbd7a33e6.png)

**Comment by Maasq** [comment]
Issue fixed by using different code to access the html file on the remote server.
