### ISSUE TITLE
FEATURE REQUEST: Bespoke Actions & Traits

### ISSUE THREAD

**Issue by The-Kergan** [Maasq/NPC-Engineer#31]
It would be helpful to be able to set up a library of Actions and Traits to call when setting up NPCs.

Eg enter a trait once and then have the ability to choose it from a list of traits pre-entered.

**Comment by Maasq** [comment]
Hiya! This is already in NPC Engineer. In the 'Options' menu, you'll find:

**_Manage Weapons.json -_** this brings up a dialogue to add new weapons to the drop down menu in the 'Actions' screen. You can delete weapons from here too.
**_Manage Actions.json -_** this brings up a dialogue to add new actions to the drop down menu in the 'Actions/Reactions/Legendary Actions/Lair Actions' screens.
**_Manage Traits.json -_** this brings up a dialogue to add new traits to the drop down menu in the 'Traits' tab.

json is just the structure for storing each of these. You can edit them directly in a text editor if you wish, although that will be a harder way to do it. The option is there though :)  This is more likely to be useful if you are merging weapons lists, or traits lists, etc 

I'll mark this as complete.

Maasq
