### ISSUE TITLE
Missing Legendary Monster section

### ISSUE THREAD

**Issue by Taboomantis** [Maasq/NPC-Engineer#32]
Working on an NIHILITH from Tome of Beasts.  Everything worked nice except the following section had no place and is missing from the monster.

REGIONAL EFFECTS
The regional effects of a nihileth’s lair are the same as that of an
aboleth, except as following.
• Water sources within 1 mile of a nihileth’s lair are not only supernaturally fouled but can spread the disease of the nihileth. A creature who drinks from such water must make a successful DC 14 Constitution check or become infected.

Dragons also have a Regional Effect as do most other legendary creatures.

**Comment by Maasq** [comment]
Hiya!

The Regional Effects just go in to the 'Description'. There's no function for them in Fantasy Grounds and none of the official monsters such as dragons have them anywhere other than the 'Other' tab (ie the description).

Hope this helps!

**Comment by Taboomantis** [comment]
Thanks, done it.
