### ISSUE TITLE
Images Disappear

### ISSUE THREAD

**Issue by teak421** [Maasq/NPC-Engineer#34]
Hi.
I own Tome of Beasts and I wanted to create a Monster Manual module with the app.  When I create a NPC and add an image to it (both token / image) it saves fine. Update project works perfectly and all is good inside of FG.  But, let's say I made a mistake and I go back into the NPC and change something (I actually forgot some text) and I click save and update project.  But, now when I go into FG, both the image and the token are missing.  I then went back into the tool and loaded the NPC in question and noticed that the token and image was missing.
I was sure to save any time I made any changes.  I hope this is enough description and apologies if this is a user error.

**Comment by teak421** [comment]
The issue was an end-user error...me!  What I did was copy the images from Roll20 and put on my desktop and then inside the application, I added the token and image.  I then deleted the images from my desktop thinking it was copied to the correct FG folder.   Basically, I incorrectly assumed that it would copy the images/tokens to a final destination.  Please close this issue.  

Thanks again for this application, it's amazing!

**Comment by Maasq** [comment]
Hiya, I am sorry I am so far behind this answer. NPCE **should** copy images to its own directory if you have the option set to do it, and it is set by default. I seem to have some vague recollection of there being a permissions problem with files on the desktop, so perhaps store the images somewhere else?

Let me know if there's anything else!
