### ISSUE TITLE
Fresh Windows 10 Install and get the following error...

### ISSUE THREAD

**Issue by MythikWolf** [Maasq/NPC-Engineer#4]
![image](https://user-images.githubusercontent.com/4665296/34509335-b8837d42-effd-11e7-8d36-50cdf82ef021.png)

**Comment by MythikWolf** [comment]
Easily resolved on a fresh OS but something to think about maybe?

**Comment by Maasq** [comment]
I have added MSVCR100.dll to the installation pack. It works fine sitting in NPC Engineer's directory.
Thanks for pointing this out.
